
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mos-postgres-pvc
  namespace: elmoselmos-dev
  labels:
    name: postgresmos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-postgres-name
  storageClassName: gp2
  volumeMode: Filesystem

